### ISSUE TITLE
git push doesnt work after creation

### ISSUE THREAD

**Issue by skywinder** [clauswitt/bitbucket-cli#3]
`git bb repository create` creates origin reference to:  `origin    git@bitbucket.org:skywinder/TipsAndTrics.git`

`git push` got error: 

> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

After changing remote to: `https://skywinder@bitbucket.org/skywinder/tipsandtrics.git` push starts work as expected

**Comment by clauswitt** [comment]
abandonned. Sorry.
